use_frameworks!

platform :ios, '12.0'

target 'JWStackTransition_Example' do
  pod 'JWStackTransition', :path => '../'
  
  pod 'SnapKit'

  target 'JWStackTransition_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
